### PR TITLE
Async simulate_until

### LINKED ISSUE #694: It is no longer clear how execution::simulate_until() should work with indeterminate end time
This is related to the recent removal of fibers from the code, in particular from the `cosim::execution` API. It is no longer clear to me how the following code should work, or if it is at all valid:
```cpp
auto exe = cosim::execution( /* ... */ );
// Add stuff to the execution
// ...
auto stopped = exe.simulate_until(std::nullopt_t);
```
In the old version, `simulate_until()` was an async function that returned immediately, and its return value was a `future` which could be queried for the simulation status.

Now that it's no longer async, should it even be possible to pass it an indeterminate end time? Won't it just hang? One may think that one could call `exe.stop_simulation()` from some other thread, but the code is not thread safe. (`stop_simulation()` simply sets a non-atomic, non-mutex-protected `bool` variable.)

Running the simulation asynchronously until it's stopped by the user is a real use case. I believe the Demo App does it. So I think this needs to be cleared up pretty quickly.

### PR DESCRIPTION
**Pull request by markaren**
Less intrusive and simpler alternative to #695 

Resolves #694

### CODE REVIEW

**Comment by restenb** [comment]
Yes, this is what I had in mind as well, a minimal implementation that fixes both issues noted by @kyllingstad in #694.

**Comment by kyllingstad** [comment]
Maybe we can do it even simpler: Leave `simulate_until()` as is, keeping the optional argument, and _just_ make `stop_simulation()` threadsafe as done here. Then we can specify in the documentation that `simulate_until({})` will block the current thread indefinitely, but that it is safe to stop it from another thread. (The fact that `stop_simulation()` is threadsafe should be specified in _its_ documentation too.)

Then the user can choose how to implement the multithreading. Maybe they want to use `std::async()` for simplicity, but they could also prefer to have more control over the threading. (For example, some applications may have a business thread and a UI thread, or use a custom thread pool, or use `boost::thread` rather than `std::thread`, etc. etc. etc.).

**Comment by markaren** [comment]
The existing signature of `simulate_until` (rather than void and non-optional parameter) was kept in order for clients to override the behaviour of the async version. I still think there is value in adding a default non-blocking function.

**Comment by restenb** [comment]
I'm OK with keeping the built-in `simulate_until_async` option, clients that want to handle threading can use the blocking version. This could also be noted in the documentation. 

I have one code comment: On line 119 of `execution.cpp` , we `return !stopped_`. I assume this has to be changed to `return !stopped_.load()` to ensure thread safety also for the `is_running()` function.

**Comment by markaren** [comment]
According to stackoverflow `load/store` is already being called implicitly.

**Review by kyllingstad — APPROVED** [review]
Looks good to me!

**Pull request merged**
